// Our task server with initial scaffolding generated by swagger-codegen.
//
// Eli Bendersky [https://eli.thegreenplace.net]
// This code is in the public domain.
package main

import (
	"log"
	"net/http"
	"os"

	"example.com/internal/swagger"
)

func main() {
	log.Printf("Server started")
	router := swagger.NewRouter()
	log.Fatal(http.ListenAndServe("localhost:"+os.Getenv("SERVERPORT"), router))
}
