[package]
name = "serde-rayon-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
rayon = "1.5.1"
serde = "1.0.136"
serde_json = "1.0.78"
